### PR TITLE
Making an atom without an initial value should return possibly undefined

### LINKED ISSUE #116: Type safety issue with undefined store value
In TypeScript, the initial value of an atom is typed as optional. This means the following would typecheck, but fail with a runtime error:
```ts
import { atom } from "nanostores"
import { useStore } from "@nanostores/react"

const message = atom<string>()

export default function App() {
  const currentMessage = useStore(message)
  const firstWord = currentMessage.split(" ")[0]
  return <p>{firstWord}</p>
}
```
[Sandbox link](https://codesandbox.io/s/practical-galileo-zt17m5?file=/src/App.tsx:0-266)

I would suggest either...

- make the initialValue argument required
- add an overload which returns `WritableAtom<T | undefined>`

...although both could be breaking changes for TS users :sweat_smile:

### PR DESCRIPTION
**Pull request by itsMapleLeaf**
Closes #116

### CODE REVIEW

**Comment by ai** [comment]
Looks good. I am going to party now. I will try to merge it tomorrow or after tomorrow.

**Comment by ai** [comment]
Can I just fix `pnpm test` or CI?

**Comment by itsMapleLeaf** [comment]
Oh, I didn't notice those errors :upside_down_face: You can go ahead and fix them

**Comment by itsMapleLeaf** [comment]
Never mind, they were fairly straightforward fixes :sweat_smile:

**Pull request merged**
